server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.232.196:3306/spring-cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mazhen123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mazn.springcloud.entites
eureka:
  client:
    #表示是否将自己注册进Eureka，默认为true
    register-with-eureka: true
    #表示是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须配置为true才能配个ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka